import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { css } from "@emotion/react";
import formik from "Formik";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>마이티 계산기</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-[585px] min-w-[320px] bg-[#D9D9D9] mx-auto px-[30px] py-[55px]">
        <div className="flex items-center justify-between">
          <button
            type="button"
            className="text-white bg-[#FF0000] w-[105px] h-[40px] rounded-[5px]"
          >
            리셋
          </button>
          <span>마이티 계산기</span>
          <button
            type="button"
            className="text-black bg-white w-[105px] h-[40px] rounded-[5px]"
          >
            계산법
          </button>
        </div>

        <div className="grid grid-cols-5 mt-[32px]">
          <input
            type="text"
            className="h-[40px] flex items-center justify-center border border-black focus:outline-none px-[5px]"
          />
          <input
            type="text"
            className="h-[40px] flex items-center justify-center border border-black focus:outline-none px-[5px]"
          />
          <input
            type="text"
            className="h-[40px] flex items-center justify-center border border-black focus:outline-none px-[5px]"
          />
          <input
            type="text"
            className="h-[40px] flex items-center justify-center border border-black focus:outline-none px-[5px]"
          />
          <input
            type="text"
            className="h-[40px] flex items-center justify-center border border-black focus:outline-none px-[5px]"
          />
        </div>
        <button type="button" className="w-[105px] h-[40px] bg-white mx-auto">
          이름 수정 완료
        </button>
      </div>
    </>
  );
}
